### ISSUE TITLE
node_modules inside the docker

### ISSUE THREAD

**Issue by thiagobenine** [kerbe/docker-expo#1]
Is it possible to alter the Dockerfile  to make it run npm install inside the docker?

**Comment by kerbe** [comment]
Hello @thiagobenine, and I'm sorry for not spotting this issue in this long time! Before I dive deeper in this, is this request still relevant for you, or have you managed to solve your problem otherwise?

**Comment by kerbe** [comment]
Now that I've recovered a bit from this shock that I haven't received notifications from these issues in this repo, I might have best practice solution for you.

You create own Dockerfile that extends this one. In that Dockerfile you make alterations needed. Either running separate RUN command which runs npm install (which gets ran only when container is built), or you could create separate entrypoint script, which runs npm install every time you start new container, and once that is done it starts actual expo-cli.

Docker container should be designed to do only one job, so I don't think making this container to run npm install is best way. 

You can of course run `docker exec` commands, which gets executed inside container. I use that to install extra packages to my projects quite frequently.

**Comment by kerbe** [comment]
Closing this issue, as there hasn't been any reply. If problem still persist, don't hesitate to comment here & ping me.
